"""create counties and county_year_settings

Revision ID: 3905480dfacd
Revises: f000f35cac1e
Create Date: 2026-05-11 14:26:38.265515

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3905480dfacd"
down_revision: str | Sequence[str] | None = "f000f35cac1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counties",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("fips_code", sa.String(length=5), nullable=True),
        sa.Column("filing_office_name", sa.String(length=255), nullable=True),
        sa.Column("filing_office_address", sa.String(length=500), nullable=True),
        sa.Column("filing_office_phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("length(state) = 2", name=op.f("ck_counties_ck_counties_state_length")),
        sa.CheckConstraint(
            "state = upper(state)", name=op.f("ck_counties_ck_counties_state_uppercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_counties")),
        sa.UniqueConstraint("state", "slug", name="uq_counties_state_slug"),
        schema="keystone",
    )
    op.create_index("ix_counties_state", "counties", ["state"], unique=False, schema="keystone")
    op.create_table(
        "county_year_settings",
        sa.Column("county_id", sa.UUID(), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("clr_factor", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("par", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("appeal_deadline", sa.String(length=50), nullable=True),
        sa.Column("last_reassessment_year", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "clr_factor IS NULL OR clr_factor > 0",
            name=op.f("ck_county_year_settings_ck_county_year_settings_clr_positive"),
        ),
        sa.CheckConstraint(
            "tax_year >= 2000 AND tax_year <= 2100",
            name=op.f("ck_county_year_settings_ck_county_year_settings_tax_year_range"),
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["keystone.counties.id"],
            name=op.f("fk_county_year_settings_county_id_counties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_county_year_settings")),
        sa.UniqueConstraint(
            "county_id", "tax_year", name="uq_county_year_settings_county_id_tax_year"
        ),
        schema="keystone",
    )
    op.execute("""
        CREATE TRIGGER trg_counties_updated_at
        BEFORE UPDATE ON keystone.counties
        FOR EACH ROW
        EXECUTE FUNCTION keystone.set_updated_at();
    """)
    op.execute("""
        CREATE TRIGGER trg_county_year_settings_updated_at
        BEFORE UPDATE ON keystone.county_year_settings
        FOR EACH ROW
        EXECUTE FUNCTION keystone.set_updated_at();
    """)
    op.create_index(
        "ix_county_year_settings_county_id_tax_year",
        "county_year_settings",
        ["county_id", "tax_year"],
        unique=False,
        schema="keystone",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_county_year_settings_county_id_tax_year",
        table_name="county_year_settings",
        schema="keystone",
    )
    op.drop_table("county_year_settings", schema="keystone")
    op.drop_index("ix_counties_state", table_name="counties", schema="keystone")
    op.drop_table("counties", schema="keystone")
    op.execute("DROP TRIGGER IF EXISTS trg_county_year_settings_updated_at ON keystone.county_year_settings;")
    op.execute("DROP TRIGGER IF EXISTS trg_counties_updated_at ON keystone.counties;")
    # ### end Alembic commands ###
